# Workflow for executing all pull request actions
name: Pull Request
on:
  pull_request:

# cancel any existing instances of this workflow already running for this PR
concurrency: 
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }} 
  cancel-in-progress: true

jobs:
  ####################################################
  # look at the changes in the PR
  ####################################################
  changes:
    timeout-minutes: 10
    name: Inspect PR Changes
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      workflow: ${{ steps.filter.outputs.workflow }}
      src: ${{ steps.filter.outputs.src }}
      sln: 
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          src:
            - 'src/**'
          workflow:
            - '.github/workflows/**'
          

  ####################################################
  # conditionally execute checks based on changes
  ####################################################
  lint-workflow-files:
    needs: changes
    if: ${{ needs.changes.outputs.workflow == 'true' }}
    uses: ./.github/workflows/lint-github-actions.yaml
    secrets: inherit

  unit-tests:
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' || true }}
    uses: ./.github/workflows/unit-tests.yaml
    secrets: inherit

  ####################################################
  # make sure all required jobs resolved
  ####################################################
  check:
    if: always()
    runs-on: ubuntu-latest
    needs:
    - lint-workflow-files
    - unit-tests
    # Unity tests are slow, so we dont block on them for the 'required' job
    # We want to report the results but still let developers merge their PR
    # - unity-tests
    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        allowed-skips: lint-workflow-files, unit-tests
        jobs: ${{ toJSON(needs) }}